### PR TITLE
Fix GLib-CRITIAL on Glib::Source->remove for One-Time Timeout Source

### LINKED ISSUE #768: GLib-CRITICAL messages on Glib::Source->remove for one-time Timeout Source
#### Brief summary of issue
The CRITICAL message means freed Source ID is still recorded and used to remove source already removed.
It implies `shutter` is on risk that if another source is reusing the source ID, it would be removed by mistake. Though we are lucky this round and only get the CRITICAL message.

Involved since 2008/2009, and once reported as #198

#### Steps to reproduce the issue

1. start shutter 
2. take screenshot
3. quit shutter

#### Error output
```
GLib-CRITICAL **: Source ID 436 was not found when attempting to remove it at /usr/bin/shutter line 7094.
```

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:

One-Time Timeout Sources  are passed to `Glib::Source->remove` in `shutter` and `ShutterNotification.pm`. 

The callback should reset ID recorded, then ID check is possible to avoid unexpected `remove` call.

### PR DESCRIPTION
**Pull request by Tao-T**
One-Time Timeout Source would be auto removed when callback ended. Then the Source ID is freed to a pool for reuse and can be assigned to other new source. Hitting a freed ID means the program on risk of wrongly hitting a reused ID, which is unexpected.

This commit fixes the usage of one-time Timeout sources by resetting ID records in callbacks and checking them before Source->remove calls. Also, some unused Source->remove code cleaned up in this commit.

Fix shutter-project/shutter#768

### CODE REVIEW

**Comment by DarthGandalf** [comment]
Thanks for all these PRs!

You didn't really need to open issues separately - a PR which fixes the issue would be enough

File: share/shutter/resources/modules/Shutter/App/ShutterNotification.pm [hunk 1]
```diff
@@ -155,7 +155,7 @@ sub new {
 
 				#remove old handler
 				if (defined $self->{_enter_notify_timeout}) {
```
Comment (DarthGandalf) [inline share/shutter/resources/modules/Shutter/App/ShutterNotification.pm]: maybe instead remove "defined" from here?

Comment (Tao-T) [reply share/shutter/resources/modules/Shutter/App/ShutterNotification.pm]: Yes less is more, fixed in b69aa17
